### ISSUE TITLE
SkyTG24 live

### ISSUE THREAD

**Issue by sasagr** [nixxo/plugin.video.skyvideoitalia#1]
Would it be possible to add the live stream of SkyTG24?

**Comment by nixxo** [comment]
yes, I'll look into it for the next release.

**Comment by nixxo** [comment]
@sasagr se puoi, riusciresti ad installarti il mio repository: https://github.com/nixxo/repository.nixxo/releases/tag/v1.0.1 e verificare se anche a te funzionano i live srteam che ho aggiunto?

Io ho provato solo su kodi19 su PC con win7_x86 e kodi19 su vero4k con OSMC.

Guisto per avere un feedback diverso prima di inviare la nuova versione al repo ufficiale.

**Comment by sasagr** [comment]
Ho provato anche io su vero4k e sembra funzionare. Ho solo un problema con skytg24 ma è dovuto al fatto che è geo-restricted ed io non sono in Italia. Gli altri canali sono ok.
Ho anche provato sulla firestick4k dove è più facile avere una vpn e ho questo errore (sia con vpn che senza).
 
NO JSON DATA FOUND

https://paste.kodi.tv/elexomuvok

Grazie

**Comment by nixxo** [comment]
> Ho solo un problema con skytg24 ma è dovuto al fatto che è geo-restricted ed io non sono in Italia.

In teoria tg24 non è geo-restricted essendo news mentre cielo e tv8 dovrebbero esserlo in quanto commerciali

tg24, vedi il campo geoblock:
```
    "ext": "hls",
    "geoblock": 0,
    "last_modify_date": "19/11/2021 14:49:59",
    "meta_description": "Scopri le ultime news nella diretta video in streaming di Sky TG24.",
    "meta_title": "Diretta news video in live streaming - Sky TG24 | Sky",
```

mentre per cielo e tv8 è impostato a 1.
Provo a installarmi una vpn e fare qualche prova.

**Comment by nixxo** [comment]
Allora, fatta qualche prova:

- cielo e tv8 funzionano come dovrebbero. Con IP italiano funzionano, con IP straniero il plugin dice "Url non trovato".
- Lo stream 24h di sky (il quarto nella lista) funziona sempre e non è GEO bloccato.
- TG24 in teoria non dovrebbe essere GEO bloccato ma in realtà lo è. Quando mando una richiesta al sito, mi restituisce l'url del video in streaming ma poi quell'url non è riproducibile. Probabilmente hanno sbagliato loro a settare qualcosa sui server. Io gli ho scritto un tweet, magari fixano: https://twitter.com/cnico/status/1463862076108066829

**Comment by sasagr** [comment]
ok, io nel frattempo ho riprovato aggirando in qualche modo i blocchi geografici e funziona tutto bene.
A proposito a cosa serve il canale "Le dirette live di Sky"?

**Comment by nixxo** [comment]
è uno stream senza commenti 24/7 tipo webcam. L'altro giorno quando l'ho provato stavano trasmettendo dei soccorritori che stavano lavorando ad una abitazione crollata, e per l'appunto, c'era questo stream in diretta puntato su questa abitazione crollata e dei soccorritori li con il trattore ecc che spostavano le macerie.

Credo sia solamente una ripetizione di qualche webcam o simili che attivano quando ci sono per l'appunto fatti del genere.

questo è l'url degli stream:
`https://apid.sky.it/vdp/v1/getLivestream?id=1`
e se cambi in numero in fondo fai passare i canali disponibili. C'e' pure xfactor e skysport ma sono a pagamento.

**Comment by sasagr** [comment]
si avevo già studiato il tuo codice e avevo fatto qualche prova e visto che per sky sport manca lo streaming_url :(

**Comment by nixxo** [comment]
inviato sul repo di Kodi: https://github.com/xbmc/repo-plugins/pull/3791
