### ISSUE TITLE
Impossibile riprodurre

### ISSUE THREAD

**Issue by Gythion** [nixxo/plugin.video.skyvideoitalia#2]
E' da domenica che il playback è troppo lento o non parte proprio. Se vai sul loro sito, la riproduzione è normale. Puoi risolvere?

**Comment by nixxo** [comment]
Ciao, puoi essere più preciso cosa intendi per lento.
Quali contenuti? I video o le dirette streaming?
Che impostazioni hai?
Su che device stai utilizzando Kodi?

**Comment by Gythion** [comment]
https://is.gd/fT0fnA

**Comment by nixxo** [comment]
ok, grazie del log.

scorrendolo mi pare sia un problema di configurazione di Kodi che non attiva correttamente il decoder audio/video.
Non son cose di cui son particolarmente esperto, per quel che capisco leggendo il log:
- c'è un warning che alcune funzioni directX non sono supportate,
- poi il decoder fallisce a "leggere" correttamente il video
-  e comincia a rallentare.

```
WARNING <general>: DXVA::CContext::CreateContext: using app d3d11 device for decoding due extended NV12 shared textures it's not supported.
...
ERROR <general>: ffmpeg[0x1f13ce9e2e0X]: [h264] hardware accelerator failed to decode picture
...
INFO <general>: CVideoPlayerAudio::Process - stream stalled
```

Il plugin di per se non ha alcun problema, fa quello che deve fare. Legge il sito e restituisce il link del video a Kodi. Tutto il resto dipende da Kodi.

2 possibili cause:
- Hai aggiornato windows o qualche driver e ha creato incompatibilità con Kodi (cosa forse più probabile vedendo il Log)
- Sky ha cambiato la codifica dei video e non vengono letti bene dalla tua versione di Kodi (a me funzionano)

L'unica cosa che potresti provare a cambiare del plugin è nelle impostazioni lasciar gestire la qualità ad InputStream Adaptive

**Comment by Gythion** [comment]
Ok, risolto, non sapevo ci fosse l'impostazione "InputStream Adaptive". Grazie per la celerità
