### ISSUE TITLE
Impossibile riprodurre con update InputStream

### ISSUE THREAD

**Issue by Gythion** [nixxo/plugin.video.skyvideoitalia#3]
Come da oggetto, con l'ultimo update di InputStream, mi dà errore al momento del playback, ed ho dovuto impostare "Qualità media". https://is.gd/zMMI6j

**Comment by nixxo** [comment]
Ciao, grazie di usare il mio plugin.

Ogni tanto mi domando se qualcuno lo usa e perciò mi fa piacere.

Come vedi il plugin è un po' che non viene aggiornato perché sinceramente non mi son mai preoccupato di testarlo su Kodi20.

Io ho un lettore OSMC con Kodi 19.5 e inputstream 19.0.7 e mi funziona come dovrebbe.

Se puoi essere specifico nelle versioni da te utilizzate e magari postare un log abilitando la funzionalità "sviluppatore" nel plugin così da avere qualche info in più mi faresti una cortesia.

**Comment by Gythion** [comment]
https://is.gd/4pfbmq

**Comment by nixxo** [comment]
Ok, devi installare "InputStream Helper".

In teoria dovrebbe suggerire in automatico di installarlo qualno hai installato il plugin di Sky. Forse lo hai disabilitato in seguito o qualcosa non ha funzionato nell'installazione.

Provo a fare qualche prova installando Kodi 20 e vedendo come si comporta.

Fammi sapere se installando "Inputstream Helper" si risolve la cosa.

Oggi pomeriggio guardo la MotoGP 😜, vedrò se ho tempo stasera.

**Comment by Gythion** [comment]
Installato e problema risolto, ma viene richiesto come componente opzionale
